# Generated by Django 5.1.6 on 2025-06-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album')),
                ('artists', models.ManyToManyField(related_name='songs', to='artists.artist')),
                ('genres', models.ManyToManyField(related_name='songs', to='genres.genre')),
            ],
        ),
    ]
