# Generated by Django 5.1.6 on 2025-05-08 13:49

from django.db import migrations

def clear_audio_files(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    Song.objects.all().update(audio_file=None)

class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_artists'),
    ]

    operations = [
        migrations.RunPython(clear_audio_files, migrations.RunPython.noop),
    ]