# Generated by Django 5.1.6 on 2025-05-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_remove_audio_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
