# Generated by Django 5.1.6 on 2025-02-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subcription_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
