# Generated by Django 5.1.6 on 2025-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.URLField(blank=True, default='https://d1m06rjnqs2z9j.cloudfront.net/playlist-cover/placeholder.png', null=True),
        ),
    ]
