# Generated by Django 5.1.6 on 2025-02-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chathistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('bot_id', models.AutoField(primary_key=True, serialize=False)),
                ('llm_model', models.CharField(max_length=255)),
                ('chatHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chathistory.chathistory')),
            ],
        ),
    ]
