# Generated by Django 5.1.6 on 2025-05-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('songs', '0007_remove_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recommended_songs',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='songs.song'),
        ),
    ]
